[package]
name = "litechain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1"
rand = "0.7"
sha2 = "0.10.8"
dashmap = "4.0"
hex = "0.4.3"
